export const TableData = [
  {
    id: "#1001",
    customer: "Abel Bekele",
    product: "iPhone 15 Pro",
    amount: "$1,250",
    payment: "Telebirr",
    status: "Delivered",
    date: "Jul 28, 2026",
    from: "customer-B",
  },
  {
    id: "#1002",
    customer: "Hana Alemu",
    product: "Nike Shoes",
    amount: "$180",
    payment: "CBE",
    status: "Pending",
    date: "Jul 28, 2026",
    from: "customer-A",
  },
  {
    id: "#1003",
    customer: "Samuel T.",
    product: "Headphones",
    amount: "$75",
    payment: "Cash",
    status: "Processing",
    date: "Jul 27, 2026",
    from: "customer-C",
  },
  {
    id: "#1004",
    customer: "Miki D.",
    product: "Laptop Bag",
    amount: "$45",
    payment: "Chapa",
    status: "Cancelled",
    date: "Jul 27, 2026",
    from: "customer-D",
  },
];
