import {
  LayoutDashboard,
  Package,
  FolderTree,
  Tags,
  ShoppingCart,
  Users,
  Store,
  CreditCard,
  Receipt,
  TicketPercent,
  Star,
  MessageSquare,
  Bell,
  Boxes,
  Truck,
  Undo2,
  BarChart3,
  FileBarChart,
  TrendingUp,
  Megaphone,
  Image,
  Newspaper,
  CircleHelp,
  Settings,
  ShieldCheck,
  User,
  History,
  DatabaseBackup,
  LifeBuoy,
  LogOut,
} from "lucide-react";
import { Link } from "react-router-dom";

export const menuItems = [
  { icon: <LayoutDashboard />, text: "Dashboard", path: "/dashboard" },
  { icon: <Package />, text: "Products", path: "/product" },
  { icon: <FolderTree />, text: "Categories", path: "/category" },
  { icon: <Tags />, text: "Brand", path: "/brand" },
  { icon: <ShoppingCart />, text: "Orders", path: "/order" },
  { icon: <Users />, text: "Customers", path: "/customer" },
  { icon: <Store />, text: "Seller", path: "/seller" },
  { icon: <CreditCard />, text: "Payments", path: "/payment" },
  { icon: <Receipt />, text: "Transactions", path: "/transaction" },
  { icon: <TicketPercent />, text: "Cupon", path: "/cupon" },
  { icon: <Star />, text: "Reviews", path: "/review" },
  { icon: <MessageSquare />, text: "Messages", path: "/message" },
  { icon: <Bell />, text: "Notifications", path: "/notification" },
  { icon: <Boxes />, text: "Inventory", path: "/inventory" },
  { icon: <Truck />, text: "Shipping", path: "/shipping" },
  { icon: <Undo2 />, text: "Returns", path: "/return" },
  { icon: <BarChart3 />, text: "Analaytics", path: "/analaytic" },
  { icon: <FileBarChart />, text: "Reports", path: "/report" },
  { icon: <TrendingUp />, text: "Sales", path: "/sale" },
  { icon: <Megaphone />, text: "Marketing", path: "/market" },
  { icon: <Image />, text: "Banners", path: "/banner" },
  { icon: <Newspaper />, text: "Blogs", path: "/blog" },
  { icon: <CircleHelp />, text: "FAQ", path: "/question" },
  { icon: <Settings />, text: "Settings", path: "/setting" },
  { icon: <ShieldCheck />, text: "Roles & Permissions", path: "/role" },
  { icon: <User />, text: "Profile", path: "/profile" },
  { icon: <History />, text: "Activity Logs", path: "/activity" },
  { icon: <DatabaseBackup />, text: "Backup", path: "/backup" },
  { icon: <LifeBuoy />, text: "Support", path: "/support" },
  { icon: <LogOut />, text: "LOgout", path: "/logout" },
];
